package cz.muni.fi.xsmeral.echoapp.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11.redhat-3
 * 2014-12-30T20:01:44.036+01:00
 * Generated source version: 2.7.11.redhat-3
 * 
 */
@WebServiceClient(name = "EchoService", 
                  wsdlLocation = "http://server:8080/echoapp/EchoService?wsdl",
                  targetNamespace = "http://xsmeral.fi.muni.cz/echoapp/ws") 
public class EchoService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xsmeral.fi.muni.cz/echoapp/ws", "EchoService");
    public final static QName Echo = new QName("http://xsmeral.fi.muni.cz/echoapp/ws", "Echo");
    static {
        URL url = null;
        try {
            url = new URL("http://server:8080/echoapp/EchoService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EchoService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://server:8080/echoapp/EchoService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EchoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EchoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EchoService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EchoService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EchoService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EchoService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns WsEchoEndpoint
     */
    @WebEndpoint(name = "Echo")
    public WsEchoEndpoint getEcho() {
        return super.getPort(Echo, WsEchoEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsEchoEndpoint
     */
    @WebEndpoint(name = "Echo")
    public WsEchoEndpoint getEcho(WebServiceFeature... features) {
        return super.getPort(Echo, WsEchoEndpoint.class, features);
    }

}
