package cz.muni.fi.xsmeral.echoapp.ws;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11.redhat-3
 * 2014-12-30T20:01:44.003+01:00
 * Generated source version: 2.7.11.redhat-3
 * 
 */
@WebService(targetNamespace = "http://xsmeral.fi.muni.cz/echoapp/ws", name = "WsEchoEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface WsEchoEndpoint {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://xsmeral.fi.muni.cz/echoapp/ws", className = "cz.muni.fi.xsmeral.echoapp.ws.SayHello")
    @WebMethod
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://xsmeral.fi.muni.cz/echoapp/ws", className = "cz.muni.fi.xsmeral.echoapp.ws.SayHelloResponse")
    public java.lang.String sayHello();
}
